import { Song } from '@/types/song';

export const songs: Song[] = [
  {
    key: '3 Doors Down - Here Without You',
    url: 'mix/3 Doors Down - Here Without You.mp3',
    answer: '3 Doors Down - Here Without You',
    tag: 'mix',
  },
  {
    key: 'ABBA - The Winner Takes It All',
    url: 'mix/ABBA - The Winner Takes It All.mp3',
    answer: 'ABBA - The Winner Takes It All',
    tag: 'mix',
  },
  {
    key: 'AC DC - You Shook Me All Night Long',
    url: 'mix/AC DC - You Shook Me All Night Long.mp3',
    answer: 'AC DC - You Shook Me All Night Long',
    tag: 'mix',
  },
  {
    key: 'Adele - Rolling in the Deep',
    url: 'mix/Adele - Rolling in the Deep.mp3',
    answer: 'Adele - Rolling in the Deep',
    tag: 'mix',
  },
  {
    key: "Aerosmith - I Don't Want to Miss a Thing",
    url: "mix/Aerosmith - I Don't Want to Miss a Thing.mp3",
    answer: "Aerosmith - I Don't Want to Miss a Thing",
    tag: 'mix',
  },
  {
    key: 'Alice In Chains - Would',
    url: 'mix/Alice In Chains - Would.mp3',
    answer: 'Alice In Chains - Would',
    tag: 'mix',
  },
  {
    key: 'Alphaville - Forever Young',
    url: 'mix/Alphaville - Forever Young.mp3',
    answer: 'Alphaville - Forever Young',
    tag: 'mix',
  },
  {
    key: 'Amy Winehouse - Rehab',
    url: 'mix/Amy Winehouse - Rehab.mp3',
    answer: 'Amy Winehouse - Rehab',
    tag: 'mix',
  },
  {
    key: 'Billy Joel - Uptown Girl',
    url: 'mix/Billy Joel - Uptown Girl.mp3',
    answer: 'Billy Joel - Uptown Girl',
    tag: 'mix',
  },
  {
    key: 'Black - Wonderful Life',
    url: 'mix/Black - Wonderful Life.mp3',
    answer: 'Black - Wonderful Life',
    tag: 'mix',
  },
  {
    key: "Bon Jovi - Livin' On A Prayer",
    url: "mix/Bon Jovi - Livin' On A Prayer.mp3",
    answer: "Bon Jovi - Livin' On A Prayer",
    tag: 'mix',
  },
  {
    key: 'Boston - More Than a Feeling',
    url: 'mix/Boston - More Than a Feeling.mp3',
    answer: 'Boston - More Than a Feeling',
    tag: 'mix',
  },
  {
    key: 'Bruce Springsteen - Born in the U.S.A',
    url: 'mix/Bruce Springsteen - Born in the U.S.A.mp3',
    answer: 'Bruce Springsteen - Born in the U.S.A',
    tag: 'mix',
  },
  {
    key: "Bryan Adams - Summer Of '69",
    url: "mix/Bryan Adams - Summer Of '69.mp3",
    answer: "Bryan Adams - Summer Of '69",
    tag: 'mix',
  },
  {
    key: 'Coldplay - Viva La Vida',
    url: 'mix/Coldplay - Viva La Vida.mp3',
    answer: 'Coldplay - Viva La Vida',
    tag: 'mix',
  },
  {
    key: "Coolio, L.V. - Gangsta's Paradise",
    url: "mix/Coolio, L.V. - Gangsta's Paradise.mp3",
    answer: "Coolio, L.V. - Gangsta's Paradise",
    tag: 'mix',
  },
  {
    key: "Crowded House - Don't Dream It's Over",
    url: "mix/Crowded House - Don't Dream It's Over.mp3",
    answer: "Crowded House - Don't Dream It's Over",
    tag: 'mix',
  },
  {
    key: 'Cutting Crew - (I Just) Died In Your Arms',
    url: 'mix/Cutting Crew - (I Just) Died In Your Arms.mp3',
    answer: 'Cutting Crew - (I Just) Died In Your Arms',
    tag: 'mix',
  },
  {
    key: 'Depeche Mode - Enjoy the Silence',
    url: 'mix/Depeche Mode - Enjoy the Silence.mp3',
    answer: 'Depeche Mode - Enjoy the Silence',
    tag: 'mix',
  },
  {
    key: 'Dire Straits - Sultans Of Swing',
    url: 'mix/Dire Straits - Sultans Of Swing.mp3',
    answer: 'Dire Straits - Sultans Of Swing',
    tag: 'mix',
  },
  {
    key: 'Don McLean - American Pie',
    url: 'mix/Don McLean - American Pie.mp3',
    answer: 'Don McLean - American Pie',
    tag: 'mix',
  },
  {
    key: 'Duran Duran - Ordinary World',
    url: 'mix/Duran Duran - Ordinary World.mp3',
    answer: 'Duran Duran - Ordinary World',
    tag: 'mix',
  },
  {
    key: 'Eagles - Hotel California',
    url: 'mix/Eagles - Hotel California.mp3',
    answer: 'Eagles - Hotel California',
    tag: 'mix',
  },
  {
    key: "Elvis Presley - Can't Help Falling in Love",
    url: "mix/Elvis Presley - Can't Help Falling in Love.mp3",
    answer: "Elvis Presley - Can't Help Falling in Love",
    tag: 'mix',
  },
  {
    key: 'Eminem - Lose Yourself',
    url: 'mix/Eminem - Lose Yourself.mp3',
    answer: 'Eminem - Lose Yourself',
    tag: 'mix',
  },
  {
    key: 'Eminem, Dido - Stan',
    url: 'mix/Eminem, Dido - Stan.mp3',
    answer: 'Eminem, Dido - Stan',
    tag: 'mix',
  },
  {
    key: 'Europe - The Final Countdown',
    url: 'mix/Europe - The Final Countdown.mp3',
    answer: 'Europe - The Final Countdown',
    tag: 'mix',
  },
  {
    key: 'Eurythmics - Sweet Dreams (Are Made of This)',
    url: 'mix/Eurythmics - Sweet Dreams (Are Made of This).mp3',
    answer: 'Eurythmics - Sweet Dreams (Are Made of This)',
    tag: 'mix',
  },
  {
    key: 'Evanescence - Bring Me To Life',
    url: 'mix/Evanescence - Bring Me To Life.mp3',
    answer: 'Evanescence - Bring Me To Life',
    tag: 'mix',
  },
  {
    key: 'Frank Sinatra - My Way',
    url: 'mix/Frank Sinatra - My Way.mp3',
    answer: 'Frank Sinatra - My Way',
    tag: 'mix',
  },
  {
    key: 'Freddie Mercury, Montserrat Caballé - Barcelona',
    url: 'mix/Freddie Mercury, Montserrat Caballé - Barcelona.mp3',
    answer: 'Freddie Mercury, Montserrat Caballé - Barcelona',
    tag: 'mix',
  },
  {
    key: 'Gotye, Kimbra - Somebody That I Used To Know',
    url: 'mix/Gotye, Kimbra - Somebody That I Used To Know.mp3',
    answer: 'Gotye, Kimbra - Somebody That I Used To Know',
    tag: 'mix',
  },
  {
    key: 'Green Day - Wake Me up When September Ends',
    url: 'mix/Green Day - Wake Me up When September Ends.mp3',
    answer: 'Green Day - Wake Me up When September Ends',
    tag: 'mix',
  },
  {
    key: 'Haddaway - What Is Love',
    url: 'mix/Haddaway - What Is Love - 7 Mix.mp3',
    answer: 'Haddaway - What Is Love',
    tag: 'mix',
  },
  {
    key: 'Hoobastank - The Reason',
    url: 'mix/Hoobastank - The Reason.mp3',
    answer: 'Hoobastank - The Reason',
    tag: 'mix',
  },
  {
    key: 'Imagine Dragons - Radioactive',
    url: 'mix/Imagine Dragons - Radioactive.mp3',
    answer: 'Imagine Dragons - Radioactive',
    tag: 'mix',
  },
  {
    key: 'Irene Cara - Flashdance...What a Feeling',
    url: 'mix/Irene Cara - Flashdance...What a Feeling.mp3',
    answer: 'Irene Cara - Flashdance...What a Feeling',
    tag: 'mix',
  },
  {
    key: 'JAY-Z, Alicia Keys - Empire State Of Mind',
    url: 'mix/JAY-Z, Alicia Keys - Empire State Of Mind.mp3',
    answer: 'JAY-Z, Alicia Keys - Empire State Of Mind',
    tag: 'mix',
  },
  {
    key: 'John Lennon - Imagine',
    url: 'mix/John Lennon - Imagine.mp3',
    answer: 'John Lennon - Imagine',
    tag: 'mix',
  },
  {
    key: 'Kansas - Dust in the Wind',
    url: 'mix/Kansas - Dust in the Wind.mp3',
    answer: 'Kansas - Dust in the Wind',
    tag: 'mix',
  },
  {
    key: 'Lady Gaga - Poker Face',
    url: 'mix/Lady Gaga - Poker Face.mp3',
    answer: 'Lady Gaga - Poker Face',
    tag: 'mix',
  },
  {
    key: 'Linkin Park - In the End',
    url: 'mix/Linkin Park - In the End.mp3',
    answer: 'Linkin Park - In the End',
    tag: 'mix',
  },
  {
    key: 'Lorde - Royals',
    url: 'mix/Lorde - Royals.mp3',
    answer: 'Lorde - Royals',
    tag: 'mix',
  },
  {
    key: 'Luis Fonsi, Daddy Yankee, Justin Bieber - Despacito',
    url: 'mix/Luis Fonsi, Daddy Yankee, Justin Bieber - Despacito.mp3',
    answer: 'Luis Fonsi, Daddy Yankee, Justin Bieber - Despacito',
    tag: 'mix',
  },
  {
    key: 'M.I.A. - Paper Planes',
    url: 'mix/M.I.A. - Paper Planes.mp3',
    answer: 'M.I.A. - Paper Planes',
    tag: 'mix',
  },
  {
    key: 'Madonna - Like a Prayer',
    url: 'mix/Madonna - Like a Prayer.mp3',
    answer: 'Madonna - Like a Prayer',
    tag: 'mix',
  },
  {
    key: 'Maroon 5 - This Love',
    url: 'mix/Maroon 5 - This Love.mp3',
    answer: 'Maroon 5 - This Love',
    tag: 'mix',
  },
  {
    key: 'Metallica - Nothing Else Matters',
    url: 'mix/Metallica - Nothing Else Matters.mp3',
    answer: 'Metallica - Nothing Else Matters',
    tag: 'mix',
  },
  {
    key: 'Mike Oldfield - Moonlight Shadow',
    url: 'mix/Mike Oldfield - Moonlight Shadow.mp3',
    answer: 'Mike Oldfield - Moonlight Shadow',
    tag: 'mix',
  },
  {
    key: 'Muse - Uprising',
    url: 'mix/Muse - Uprising.mp3',
    answer: 'Muse - Uprising',
    tag: 'mix',
  },
  {
    key: 'My Chemical Romance - Welcome to the Black Parade',
    url: 'mix/My Chemical Romance - Welcome to the Black Parade.mp3',
    answer: 'My Chemical Romance - Welcome to the Black Parade',
    tag: 'mix',
  },
  {
    key: 'Nickelback - How You Remind Me',
    url: 'mix/Nickelback - How You Remind Me.mp3',
    answer: 'Nickelback - How You Remind Me',
    tag: 'mix',
  },
  {
    key: "No Doubt - Don't Speak",
    url: "mix/No Doubt - Don't Speak.mp3",
    answer: "No Doubt - Don't Speak",
    tag: 'mix',
  },
  {
    key: 'OneRepublic - Counting Stars',
    url: 'mix/OneRepublic - Counting Stars.mp3',
    answer: 'OneRepublic - Counting Stars',
    tag: 'mix',
  },
  {
    key: 'PSY - Gangnam Style',
    url: 'mix/PSY - Gangnam Style.mp3',
    answer: 'PSY - Gangnam Style',
    tag: 'mix',
  },
  {
    key: 'Phil Collins - In The Air Tonight',
    url: 'mix/Phil Collins - In The Air Tonight.mp3',
    answer: 'Phil Collins - In The Air Tonight',
    tag: 'mix',
  },
  {
    key: 'Queen - Bohemian Rhapsody',
    url: 'mix/Queen - Bohemian Rhapsody.mp3',
    answer: 'Queen - Bohemian Rhapsody',
    tag: 'mix',
  },
  {
    key: 'R.E.M. - Losing My Religion',
    url: 'mix/R.E.M. - Losing My Religion.mp3',
    answer: 'R.E.M. - Losing My Religion',
    tag: 'mix',
  },
  {
    key: 'Radiohead - Creep',
    url: 'mix/Radiohead - Creep.mp3',
    answer: 'Radiohead - Creep',
    tag: 'mix',
  },
  {
    key: "Rag'n'Bone Man - Human",
    url: "mix/Rag'n'Bone Man - Human.mp3",
    answer: "Rag'n'Bone Man - Human",
    tag: 'mix',
  },
  {
    key: 'Rick Astley - Never Gonna Give You Up',
    url: 'mix/Rick Astley - Never Gonna Give You Up.mp3',
    answer: 'Rick Astley - Never Gonna Give You Up',
    tag: 'mix',
  },
  {
    key: 'Rihanna, JAY-Z - Umbrella',
    url: 'mix/Rihanna, JAY-Z - Umbrella.mp3',
    answer: 'Rihanna, JAY-Z - Umbrella',
    tag: 'mix',
  },
  {
    key: 'Robbie Williams - Angels',
    url: 'mix/Robbie Williams - Angels.mp3',
    answer: 'Robbie Williams - Angels',
    tag: 'mix',
  },
  {
    key: 'Sam Smith - Stay With Me',
    url: 'mix/Sam Smith - Stay With Me.mp3',
    answer: 'Sam Smith - Stay With Me',
    tag: 'mix',
  },
  {
    key: 'Soul Asylum - Runaway Train',
    url: 'mix/Soul Asylum - Runaway Train.mp3',
    answer: 'Soul Asylum - Runaway Train',
    tag: 'mix',
  },
  {
    key: 'Soundgarden - Black Hole Sun',
    url: 'mix/Soundgarden - Black Hole Sun.mp3',
    answer: 'Soundgarden - Black Hole Sun',
    tag: 'mix',
  },
  {
    key: 'Starship - We Built This City',
    url: 'mix/Starship - We Built This City.mp3',
    answer: 'Starship - We Built This City',
    tag: 'mix',
  },
  {
    key: 'Survivor - Eye of the Tiger',
    url: 'mix/Survivor - Eye of the Tiger.mp3',
    answer: 'Survivor - Eye of the Tiger',
    tag: 'mix',
  },
  {
    key: 'The Beatles - Let It Be',
    url: 'mix/The Beatles - Let It Be.mp3',
    answer: 'The Beatles - Let It Be',
    tag: 'mix',
  },
  {
    key: 'The Buggles - Video Killed The Radio Star',
    url: 'mix/The Buggles - Video Killed The Radio Star.mp3',
    answer: 'The Buggles - Video Killed The Radio Star',
    tag: 'mix',
  },
  {
    key: 'The Cardigans - Lovefool - Radio Edit',
    url: 'mix/The Cardigans - Lovefool - Radio Edit.mp3',
    answer: 'The Cardigans - Lovefool - Radio Edit',
    tag: 'mix',
  },
  {
    key: 'The Cars - Drive',
    url: 'mix/The Cars - Drive.mp3',
    answer: 'The Cars - Drive',
    tag: 'mix',
  },
  {
    key: 'The Cranberries - Zombie',
    url: 'mix/The Cranberries - Zombie.mp3',
    answer: 'The Cranberries - Zombie',
    tag: 'mix',
  },
  {
    key: 'The Goo Goo Dolls - Iris',
    url: 'mix/The Goo Goo Dolls - Iris.mp3',
    answer: 'The Goo Goo Dolls - Iris',
    tag: 'mix',
  },
  {
    key: 'The Police - Every Breath You Take',
    url: 'mix/The Police - Every Breath You Take.mp3',
    answer: 'The Police - Every Breath You Take',
    tag: 'mix',
  },
  {
    key: 'The Rolling Stones - Paint It Black',
    url: 'mix/The Rolling Stones - Paint It Black.mp3',
    answer: 'The Rolling Stones - Paint It Black',
    tag: 'mix',
  },
  {
    key: 'The Verve - Bitter Sweet Symphony',
    url: 'mix/The Verve - Bitter Sweet Symphony.mp3',
    answer: 'The Verve - Bitter Sweet Symphony',
    tag: 'mix',
  },
  {
    key: 'Twenty One Pilots - Stressed Out',
    url: 'mix/Twenty One Pilots - Stressed Out.mp3',
    answer: 'Twenty One Pilots - Stressed Out',
    tag: 'mix',
  },
  {
    key: 'U.S.A. For Africa - We Are The World',
    url: 'mix/U.S.A. For Africa - We Are The World.mp3',
    answer: 'U.S.A. For Africa - We Are The World',
    tag: 'mix',
  },
  {
    key: 'a-ha - Take on Me',
    url: 'mix/a-ha - Take on Me.mp3',
    answer: 'a-ha - Take on Me',
    tag: 'mix',
  },
  {
    key: '3 Doors Down - Be Like That',
    url: '2000/3 Doors Down - Be Like That.mp3',
    answer: '3 Doors Down - Be Like That',
    tag: '2000',
  },
  {
    key: '3 Doors Down - Kryptonite',
    url: '2000/3 Doors Down - Kryptonite.mp3',
    answer: '3 Doors Down - Kryptonite',
    tag: '2000',
  },
  {
    key: '50 Cent - In Da Club',
    url: '2000/50 Cent - In Da Club.mp3',
    answer: '50 Cent - In Da Club',
    tag: '2000',
  },
  {
    key: 'Afroman - Because I Got High',
    url: '2000/Afroman - Because I Got High.mp3',
    answer: 'Afroman - Because I Got High',
    tag: '2000',
  },
  {
    key: 'Alien Ant Farm - Smooth Criminal',
    url: '2000/Alien Ant Farm - Smooth Criminal.mp3',
    answer: 'Alien Ant Farm - Smooth Criminal',
    tag: '2000',
  },
  {
    key: 'Avril Lavigne - Complicated',
    url: '2000/Avril Lavigne - Complicated.mp3',
    answer: 'Avril Lavigne - Complicated',
    tag: '2000',
  },
  {
    key: 'Beyonce feat. Jay Z - Crazy In Love',
    url: '2000/Beyonce feat. Jay Z - Crazy In Love.mp3',
    answer: 'Beyonce feat. Jay Z - Crazy In Love',
    tag: '2000',
  },
  {
    key: "Black Eyed Peas - Let's Get It Started",
    url: "2000/Black Eyed Peas - Let's Get It Started.mp3",
    answer: "Black Eyed Peas - Let's Get It Started",
    tag: '2000',
  },
  {
    key: 'Blink 182 - All The Small Things',
    url: '2000/Blink 182 - All The Small Things.mp3',
    answer: 'Blink 182 - All The Small Things',
    tag: '2000',
  },
  {
    key: 'Bloodhound Gang - The Bad Touch',
    url: '2000/Bloodhound Gang - The Bad Touch.mp3',
    answer: 'Bloodhound Gang - The Bad Touch',
    tag: '2000',
  },
  {
    key: "Bon Jovi - It's My Life",
    url: "2000/Bon Jovi - It's My Life.mp3",
    answer: "Bon Jovi - It's My Life",
    tag: '2000',
  },
  {
    key: "Britney Spears - I'm A Slave 4 U",
    url: "2000/Britney Spears - I'm A Slave 4 U.mp3",
    answer: "Britney Spears - I'm A Slave 4 U",
    tag: '2000',
  },
  {
    key: 'Britney Spears - Toxic',
    url: '2000/Britney Spears - Toxic.mp3',
    answer: 'Britney Spears - Toxic',
    tag: '2000',
  },
  {
    key: 'Carlos Santana and Wyclef Jean - Maria, Maria',
    url: '2000/Carlos Santana and Wyclef Jean - Maria, Maria.mp3',
    answer: 'Carlos Santana and Wyclef Jean - Maria, Maria',
    tag: '2000',
  },
  {
    key: "Christina Aguilera, Lil' Kim, Mya & Pink - Lady Marmalade",
    url: "2000/Christina Aguilera, Lil' Kim, Mya & Pink - Lady Marmalade.mp3",
    answer: "Christina Aguilera, Lil' Kim, Mya & Pink - Lady Marmalade",
    tag: '2000',
  },
  {
    key: 'Coldplay - Clocks',
    url: '2000/Coldplay - Clocks.mp3',
    answer: 'Coldplay - Clocks',
    tag: '2000',
  },
  {
    key: 'Coldplay - The Scientist',
    url: '2000/Coldplay - The Scientist.mp3',
    answer: 'Coldplay - The Scientist',
    tag: '2000',
  },
  {
    key: 'Coldplay - Yellow',
    url: '2000/Coldplay - Yellow.mp3',
    answer: 'Coldplay - Yellow',
    tag: '2000',
  },
  {
    key: 'Crazy Town - Butterfly',
    url: '2000/Crazy Town - Butterfly.mp3',
    answer: 'Crazy Town - Butterfly',
    tag: '2000',
  },
  {
    key: 'Creed - One Last Breath',
    url: '2000/Creed - One Last Breath.mp3',
    answer: 'Creed - One Last Breath',
    tag: '2000',
  },
  {
    key: 'DJ Sammy - Heaven',
    url: '2000/DJ Sammy - Heaven.mp3',
    answer: 'DJ Sammy - Heaven',
    tag: '2000',
  },
  {
    key: "Destiny's Child - Survivor",
    url: "2000/Destiny's Child - Survivor.mp3",
    answer: "Destiny's Child - Survivor",
    tag: '2000',
  },
  {
    key: 'Disturbed - Down With The Sickness',
    url: '2000/Disturbed - Down With The Sickness.mp3',
    answer: 'Disturbed - Down With The Sickness',
    tag: '2000',
  },
  {
    key: 'Elvis Presley - Little Less Conversation',
    url: '2000/Elvis Presley - Little Less Conversation.mp3',
    answer: 'Elvis Presley - Little Less Conversation',
    tag: '2000',
  },
  {
    key: 'Eminem - Cleanin Out My Closet',
    url: '2000/Eminem - Cleanin Out My Closet.mp3',
    answer: 'Eminem - Cleanin Out My Closet',
    tag: '2000',
  },
  {
    key: 'Eminem - Sing For The Moment',
    url: '2000/Eminem - Sing For The Moment.mp3',
    answer: 'Eminem - Sing For The Moment',
    tag: '2000',
  },
  {
    key: 'Enrique Iglesias - Escape',
    url: '2000/Enrique Iglesias - Escape.mp3',
    answer: 'Enrique Iglesias - Escape',
    tag: '2000',
  },
  {
    key: 'Enya - Only Time',
    url: '2000/Enya - Only Time.mp3',
    answer: 'Enya - Only Time',
    tag: '2000',
  },
  {
    key: 'Evanescence - Bring Me To Life',
    url: '2000/Evanescence - Bring Me To Life.mp3',
    answer: 'Evanescence - Bring Me To Life',
    tag: '2000',
  },
  {
    key: 'Fatboy Slim - Rockafeller Skank',
    url: '2000/Fatboy Slim - Rockafeller Skank.mp3',
    answer: 'Fatboy Slim - Rockafeller Skank',
    tag: '2000',
  },
  {
    key: 'Foo Fighters - Best Of You',
    url: '2000/Foo Fighters - Best Of You.mp3',
    answer: 'Foo Fighters - Best Of You',
    tag: '2000',
  },
  {
    key: 'Foo Fighters - Learn To Fly',
    url: '2000/Foo Fighters - Learn To Fly.mp3',
    answer: 'Foo Fighters - Learn To Fly',
    tag: '2000',
  },
  {
    key: 'Gorillaz - Clint Eastwood',
    url: '2000/Gorillaz - Clint Eastwood.mp3',
    answer: 'Gorillaz - Clint Eastwood',
    tag: '2000',
  },
  {
    key: 'Gorillaz - Feel Good Inc',
    url: '2000/Gorillaz - Feel Good Inc..mp3',
    answer: 'Gorillaz - Feel Good Inc',
    tag: '2000',
  },
  {
    key: 'Green Day - Boulevard Of Broken Dreams',
    url: '2000/Green Day - Boulevard Of Broken Dreams.mp3',
    answer: 'Green Day - Boulevard Of Broken Dreams',
    tag: '2000',
  },
  {
    key: 'Gwen Stefani - Hollaback Girl',
    url: '2000/Gwen Stefani - Hollaback Girl.mp3',
    answer: 'Gwen Stefani - Hollaback Girl',
    tag: '2000',
  },
  {
    key: "Jennifer Lopez - Love Don't Cost A Thing",
    url: "2000/Jennifer Lopez - Love Don't Cost A Thing.mp3",
    answer: "Jennifer Lopez - Love Don't Cost A Thing",
    tag: '2000',
  },
  {
    key: 'Jennifer Lopez - Waiting For Tonight',
    url: '2000/Jennifer Lopez - Waiting For Tonight.mp3',
    answer: 'Jennifer Lopez - Waiting For Tonight',
    tag: '2000',
  },
  {
    key: 'Jimmy Eat World - The Middle',
    url: '2000/Jimmy Eat World - The Middle.mp3',
    answer: 'Jimmy Eat World - The Middle',
    tag: '2000',
  },
  {
    key: 'Justin Timberlake - Cry Me A River',
    url: '2000/Justin Timberlake - Cry Me A River.mp3',
    answer: 'Justin Timberlake - Cry Me A River',
    tag: '2000',
  },
  {
    key: 'Kelly Clarkson - Since U Been Gone',
    url: '2000/Kelly Clarkson - Since U Been Gone.mp3',
    answer: 'Kelly Clarkson - Since U Been Gone',
    tag: '2000',
  },
  {
    key: "Kylie Minogue - Can't Get You Out Of My Head",
    url: "2000/Kylie Minogue - Can't Get You Out Of My Head.mp3",
    answer: "Kylie Minogue - Can't Get You Out Of My Head",
    tag: '2000',
  },
  {
    key: 'Lil Jon feat. Ying Yang Twins - Get Low',
    url: '2000/Lil Jon feat. Ying Yang Twins - Get Low.mp3',
    answer: 'Lil Jon feat. Ying Yang Twins - Get Low',
    tag: '2000',
  },
  {
    key: 'Limp Bizkit - Rollin',
    url: '2000/Limp Bizkit - Rollin.mp3',
    answer: 'Limp Bizkit - Rollin',
    tag: '2000',
  },
  {
    key: 'Linkin Park - One Step Closer',
    url: '2000/Linkin Park - One Step Closer.mp3',
    answer: 'Linkin Park - One Step Closer',
    tag: '2000',
  },
  {
    key: 'Madonna - Music',
    url: '2000/Madonna - Music.mp3',
    answer: 'Madonna - Music',
    tag: '2000',
  },
  {
    key: 'Mary J Blige - Family Affair',
    url: '2000/Mary J Blige - Family Affair.mp3',
    answer: 'Mary J Blige - Family Affair',
    tag: '2000',
  },
  {
    key: "N'Sync - Bye, Bye, Bye",
    url: "2000/N'Sync - Bye, Bye, Bye.mp3",
    answer: "N'Sync - Bye, Bye, Bye",
    tag: '2000',
  },
  {
    key: "Nelly Furtado - I'm Like A Bird",
    url: "2000/Nelly Furtado - I'm Like A Bird.mp3",
    answer: "Nelly Furtado - I'm Like A Bird",
    tag: '2000',
  },
  {
    key: 'Nelly feat. Kelly Rowland - Dilemma',
    url: '2000/Nelly feat. Kelly Rowland - Dilemma.mp3',
    answer: 'Nelly feat. Kelly Rowland - Dilemma ',
    tag: '2000',
  },
  {
    key: 'No Doubt - Hey Baby',
    url: '2000/No Doubt - Hey Baby.mp3',
    answer: 'No Doubt - Hey Baby',
    tag: '2000',
  },
  {
    key: 'Outkast - Hey Ya',
    url: '2000/Outkast - Hey Ya.mp3',
    answer: 'Outkast - Hey Ya',
    tag: '2000',
  },
  {
    key: 'Outkast - Roses',
    url: '2000/Outkast - Roses.mp3',
    answer: 'Outkast - Roses',
    tag: '2000',
  },
  {
    key: 'Papa Roach - Last Resort',
    url: '2000/Papa Roach - Last Resort.mp3',
    answer: 'Papa Roach - Last Resort',
    tag: '2000',
  },
  {
    key: 'Pink - Get The Party Started',
    url: '2000/Pink - Get The Party Started.mp3',
    answer: 'Pink - Get The Party Started',
    tag: '2000',
  },
  {
    key: 'Puddle of Mudd - Blurry',
    url: '2000/Puddle of Mudd - Blurry.mp3',
    answer: 'Puddle of Mudd - Blurry',
    tag: '2000',
  },
  {
    key: 'Shaggy - Angel',
    url: '2000/Shaggy - Angel.mp3',
    answer: 'Shaggy - Angel',
    tag: '2000',
  },
  {
    key: 'Shakira - Whenever, Wherever',
    url: '2000/Shakira - Whenever, Wherever.mp3',
    answer: 'Shakira - Whenever, Wherever',
    tag: '2000',
  },
  {
    key: "Snoop Dogg - Drop It Like It's Hot",
    url: "2000/Snoop Dogg - Drop It Like It's Hot.mp3",
    answer: "Snoop Dogg - Drop It Like It's Hot",
    tag: '2000',
  },
  {
    key: 'The Calling - Wherever You Will Go',
    url: '2000/The Calling - Wherever You Will Go.mp3',
    answer: 'The Calling - Wherever You Will Go',
    tag: '2000',
  },
  {
    key: 'The White Stripes - Seven Nation Army',
    url: '2000/The White Stripes - Seven Nation Army.mp3',
    answer: 'The White Stripes - Seven Nation Army',
    tag: '2000',
  },
  {
    key: 'U2 - Vertigo',
    url: '2000/U2 - Vertigo.mp3',
    answer: 'U2 - Vertigo',
    tag: '2000',
  },
  {
    key: 'Usher, Lil Jon and Ludacris - Yeah!',
    url: '2000/Usher, Lil Jon and Ludacris - Yeah!.mp3',
    answer: 'Usher, Lil Jon and Ludacris - Yeah!',
    tag: '2000',
  },
  {
    key: 'tATu - All The Things She Said',
    url: '2000/tATu - All The Things She Said.mp3',
    answer: 'tATu - All The Things She Said',
    tag: '2000',
  },
  {
    key: '8 KAMBARYS - Kaip minimum',
    url: '2021/8 KAMBARYS - Kaip minimum.mp3',
    answer: '8 KAMBARYS - Kaip minimum',
    tag: '2021',
  },
  {
    key: 'AD - Davae',
    url: '2021/AD - Davae.mp3',
    answer: 'AD - Davae',
    tag: '2021',
  },
  {
    key: 'ATB, Topic, A7S - Your Love',
    url: '2021/ATB, Topic, A7S - Your Love.mp3',
    answer: 'ATB, Topic, A7S - Your Love',
    tag: '2021',
  },
  {
    key: 'Age Of Love - The Age Of Love',
    url: '2021/Age Of Love - The Age Of Love.mp3',
    answer: 'Age Of Love - The Age Of Love',
    tag: '2021',
  },
  {
    key: 'Agnė Sabulytė - Saulala Sadina Lylia',
    url: '2021/Agnė Sabulytė - Saulala Sadina Lylia.mp3',
    answer: 'Agnė Sabulytė - Saulala Sadina Lylia',
    tag: '2021',
  },
  {
    key: 'Alan Walker & ISÁK - Sorry',
    url: '2021/Alan Walker & ISÁK - Sorry.mp3',
    answer: 'Alan Walker & ISÁK - Sorry',
    tag: '2021',
  },
  {
    key: 'Alive - Jack Back x Fancy Inc x Roland Clark',
    url: '2021/Alive - Jack Back x Fancy Inc x Roland Clark.mp3',
    answer: 'Alive - Jack Back x Fancy Inc x Roland Clark',
    tag: '2021',
  },
  {
    key: "Alok, Sofi Tukker & INNA - It Don't Matter",
    url: "2021/Alok, Sofi Tukker & INNA - It Don't Matter.mp3",
    answer: "Alok, Sofi Tukker & INNA - It Don't Matter",
    tag: '2021',
  },
  {
    key: 'Arthy Myst - Pa moru',
    url: '2021/Arthy Myst - Pa moru.mp3',
    answer: 'Arthy Myst - Pa moru',
    tag: '2021',
  },
  {
    key: 'BICEP - APRICOTS',
    url: '2021/BICEP - APRICOTS.mp3',
    answer: 'BICEP - APRICOTS',
    tag: '2021',
  },
  {
    key: 'BORIS WAY - Pink Soldiers',
    url: '2021/BORIS WAY - Pink Soldiers.mp3',
    answer: 'BORIS WAY - Pink Soldiers',
    tag: '2021',
  },
  {
    key: 'Bardachiokas - Vaikai Po Lelijom',
    url: '2021/Bardachiokas - Vaikai Po Lelijom.mp3',
    answer: 'Bardachiokas - Vaikai Po Lelijom',
    tag: '2021',
  },
  {
    key: 'Basstrologe - Somebody To Love',
    url: '2021/Basstrologe - Somebody To Love.mp3',
    answer: 'Basstrologe - Somebody To Love',
    tag: '2021',
  },
  {
    key: 'Boomeris - Krypto Banginis',
    url: '2021/Boomeris - Krypto Banginis.mp3',
    answer: 'Boomeris - Krypto Banginis',
    tag: '2021',
  },
  {
    key: 'Boomeris - Striukės',
    url: '2021/Boomeris - Striukės.mp3',
    answer: 'Boomeris - Striukės',
    tag: '2021',
  },
  {
    key: 'Chromatics - Shadow',
    url: '2021/Chromatics - Shadow.mp3',
    answer: 'Chromatics - Shadow',
    tag: '2021',
  },
  {
    key: 'DYZGO feat. JBC - Penktadienis',
    url: '2021/DYZGO feat. JBC - Penktadienis.mp3',
    answer: 'DYZGO feat. JBC - Penktadienis',
    tag: '2021',
  },
  {
    key: 'Dimitri Vegas & Like Mike, Timmy Trumpet & Edward Maya - Feel Your Love',
    url: '2021/Dimitri Vegas & Like Mike, Timmy Trumpet & Edward Maya - Feel Your Love.mp3',
    answer:
      'Dimitri Vegas & Like Mike, Timmy Trumpet & Edward Maya - Feel Your Love',
    tag: '2021',
  },
  {
    key: 'Dwin, LIUFO & CANCUN - INVITED',
    url: '2021/Dwin, LIUFO & CANCUN - INVITED.mp3',
    answer: 'Dwin, LIUFO & CANCUN - INVITED',
    tag: '2021',
  },
  {
    key: 'Dynoro - Swimming In Your Eyes',
    url: '2021/Dynoro - Swimming In Your Eyes.mp3',
    answer: 'Dynoro - Swimming In Your Eyes',
    tag: '2021',
  },
  {
    key: 'Ed Sheeran - Bad Habits',
    url: '2021/Ed Sheeran - Bad Habits.mp3',
    answer: 'Ed Sheeran - Bad Habits',
    tag: '2021',
  },
  {
    key: 'Eelke Kleijn - Midnight Affair',
    url: '2021/Eelke Kleijn - Midnight Affair.mp3',
    answer: 'Eelke Kleijn - Midnight Affair',
    tag: '2021',
  },
  {
    key: 'Elena Tsagrinou - El diablo',
    url: '2021/Elena Tsagrinou - El diablo.mp3',
    answer: 'Elena Tsagrinou - El diablo',
    tag: '2021',
  },
  {
    key: 'Elton John & Dua Lipa - Cold Heart',
    url: '2021/Elton John & Dua Lipa - Cold Heart.mp3',
    answer: 'Elton John & Dua Lipa - Cold Heart',
    tag: '2021',
  },
  {
    key: 'EveBei - Tyli Mergaitė',
    url: '2021/EveBei - Tyli Mergaitė.mp3',
    answer: 'EveBei - Tyli Mergaitė',
    tag: '2021',
  },
  {
    key: 'Fella, Gudan & Kiki - PRRRUM',
    url: '2021/Fella, Gudan & Kiki - PRRRUM.mp3',
    answer: 'Fella, Gudan & Kiki - PRRRUM',
    tag: '2021',
  },
  {
    key: 'Filatov & Karas - Au Revoir',
    url: '2021/Filatov & Karas - Au Revoir.mp3',
    answer: 'Filatov & Karas - Au Revoir',
    tag: '2021',
  },
  {
    key: 'Fred again.. - Marea',
    url: '2021/Fred again.. - Marea.mp3',
    answer: 'Fred again.. - Marea',
    tag: '2021',
  },
  {
    key: 'Free Finga - Vien Tik Tu',
    url: '2021/Free Finga - Vien Tik Tu.mp3',
    answer: 'Free Finga - Vien Tik Tu',
    tag: '2021',
  },
  {
    key: "Gigi D'Agostino, Vize, Emotik - Never Be Lonely",
    url: "2021/Gigi D'Agostino, Vize, Emotik - Never Be Lonely.mp3",
    answer: "Gigi D'Agostino, Vize, Emotik - Never Be Lonely",
    tag: '2021',
  },
  {
    key: 'Go_A - ШУМ',
    url: '2021/Go_A - ШУМ.mp3',
    answer: 'Go_A - ШУМ',
    tag: '2021',
  },
  {
    key: 'HUGEL, Stefy de Cicco, Hugo Cantarra - 4 to the Floor',
    url: '2021/HUGEL, Stefy de Cicco, Hugo Cantarra - 4 to the Floor.mp3',
    answer: 'HUGEL, Stefy de Cicco, Hugo Cantarra - 4 to the Floor',
    tag: '2021',
  },
  {
    key: 'Hooverphonic - The Wrong Place',
    url: '2021/Hooverphonic - The Wrong Place.mp3',
    answer: 'Hooverphonic - The Wrong Place',
    tag: '2021',
  },
  {
    key: "Hypocrite - Methamphetabeat'as",
    url: "2021/Hypocrite - Methamphetabeat'as.mp3",
    answer: "Hypocrite - Methamphetabeat'as",
    tag: '2021',
  },
  {
    key: 'INNA - Up',
    url: '2021/INNA - Up.mp3',
    answer: 'INNA - Up',
    tag: '2021',
  },
  {
    key: 'Imagine Dragons - Follow You',
    url: '2021/Imagine Dragons - Follow You.mp3',
    answer: 'Imagine Dragons - Follow You',
    tag: '2021',
  },
  {
    key: 'Joshwa & Lee Foss - My Humps',
    url: '2021/Joshwa & Lee Foss - My Humps.mp3',
    answer: 'Joshwa & Lee Foss - My Humps',
    tag: '2021',
  },
  {
    key: 'Justinas Jarutis - Rami',
    url: '2021/Justinas Jarutis - Rami.mp3',
    answer: 'Justinas Jarutis - Rami',
    tag: '2021',
  },
  {
    key: 'Inga Jankauskaitė - Kas mes tokie',
    url: '2021/Kas mes tokie - Inga Jankauskaitė.mp3',
    answer: 'Inga Jankauskaitė - Kas mes tokie',
    tag: '2021',
  },
  {
    key: 'Klangkarussell - Home',
    url: '2021/Klangkarussell - Home.mp3',
    answer: 'Klangkarussell - Home',
    tag: '2021',
  },
  {
    key: 'Kydus - Gold Digger feat. Rion S',
    url: '2021/Kydus - Gold Digger feat. Rion S.mp3',
    answer: 'Kydus - Gold Digger feat. Rion S',
    tag: '2021',
  },
  {
    key: 'Leon Somov & Dileta - Back to Life',
    url: '2021/Leon Somov & Dileta Back to Life.mp3',
    answer: 'Leon Somov & Dileta - Back to Life',
    tag: '2021',
  },
  {
    key: 'Leon Somov x Saulės Kliošas - Šokių Aikštelėje',
    url: '2021/Leon Somov x Saulės Kliošas - Šokių Aikštelėje.mp3',
    answer: 'Leon Somov x Saulės Kliošas - Šokių Aikštelėje',
    tag: '2021',
  },
  {
    key: 'Lost Frequencies ft Calum Scott - Where Are You Now',
    url: '2021/Lost Frequencies ft Calum Scott - Where Are You Now.mp3',
    answer: 'Lost Frequencies ft Calum Scott - Where Are You Now',
    tag: '2021',
  },
  {
    key: 'Maceo Plex, Faithless - Insomnia 2021',
    url: '2021/Maceo Plex, Faithless - Insomnia 2021.mp3',
    answer: 'Maceo Plex, Faithless - Insomnia 2021',
    tag: '2021',
  },
  {
    key: 'Madonna Vs Sickick - Frozen',
    url: '2021/Madonna Vs Sickick - Frozen.mp3',
    answer: 'Madonna Vs Sickick - Frozen',
    tag: '2021',
  },
  {
    key: 'Majestic x Boney M. - Rasputin',
    url: '2021/Majestic x Boney M. - Rasputin.mp3',
    answer: 'Majestic x Boney M. - Rasputin',
    tag: '2021',
  },
  {
    key: 'Mancero - Momentus',
    url: '2021/Mancero - Momentus.mp3',
    answer: 'Mancero - Momentus',
    tag: '2021',
  },
  {
    key: 'Martin Garrix - Pressure',
    url: '2021/Martin Garrix - Pressure.mp3',
    answer: 'Martin Garrix - Pressure',
    tag: '2021',
  },
  {
    key: 'Masked Wolf - Astronaut in the Ocean',
    url: '2021/Masked Wolf - Astronaut in the Ocean.mp3',
    answer: 'Masked Wolf - Astronaut in the Ocean',
    tag: '2021',
  },
  {
    key: 'Matto x Ciūnys - Manęs Nėra',
    url: '2021/Matto x Ciūnys - Manęs Nėra.mp3',
    answer: 'Matto x Ciūnys - Manęs Nėra',
    tag: '2021',
  },
  {
    key: 'Mavill - Never gonna',
    url: '2021/Mavill - Never gonna.mp3',
    answer: 'Mavill - Never gonna',
    tag: '2021',
  },
  {
    key: 'Mavill - Ready',
    url: '2021/Mavill - Ready.mp3',
    answer: 'Mavill - Ready',
    tag: '2021',
  },
  {
    key: 'Meidė - Monstras',
    url: '2021/Meidė - Monstras.mp3',
    answer: 'Meidė - Monstras',
    tag: '2021',
  },
  {
    key: 'Metrik & Grafix - Overdrive',
    url: '2021/Metrik & Grafix - Overdrive.mp3',
    answer: 'Metrik & Grafix - Overdrive',
    tag: '2021',
  },
  {
    key: 'Mindosy - Stop The World',
    url: '2021/Mindosy - Stop The World.mp3',
    answer: 'Mindosy - Stop The World',
    tag: '2021',
  },
  {
    key: 'Minelli - Rampampam',
    url: '2021/Minelli - Rampampam.mp3',
    answer: 'Minelli - Rampampam',
    tag: '2021',
  },
  {
    key: 'Måneskin - ZITTI E BUONI',
    url: '2021/Måneskin - ZITTI E BUONI.mp3',
    answer: 'Måneskin - ZITTI E BUONI',
    tag: '2021',
  },
  {
    key: 'NF - CLOUDS',
    url: '2021/NF - CLOUDS.mp3',
    answer: 'NF - CLOUDS',
    tag: '2021',
  },
  {
    key: 'Nora En Pure - Aquatic',
    url: '2021/Nora En Pure - Aquatic.mp3',
    answer: 'Nora En Pure - Aquatic',
    tag: '2021',
  },
  {
    key: 'OG Version, Soliaris - Neskaičiuoju',
    url: '2021/OG Version, Soliaris - Neskaičiuoju.mp3',
    answer: 'OG Version, Soliaris - Neskaičiuoju',
    tag: '2021',
  },
  {
    key: 'OMERTA x VAIDAS BAUMILA - DEMONAI',
    url: '2021/OMERTA x VAIDAS BAUMILA - DEMONAI.mp3',
    answer: 'OMERTA x VAIDAS BAUMILA - DEMONAI',
    tag: '2021',
  },
  {
    key: 'Olivia Addams - Stranger',
    url: '2021/Olivia Addams - Stranger.mp3',
    answer: 'Olivia Addams - Stranger',
    tag: '2021',
  },
  {
    key: 'Olivia Rodrigo - drivers license',
    url: '2021/Olivia Rodrigo - drivers license.mp3',
    answer: 'Olivia Rodrigo - drivers license',
    tag: '2021',
  },
  {
    key: 'PPK - First In Space',
    url: '2021/PPK - First In Space.mp3',
    answer: 'PPK - First In Space',
    tag: '2021',
  },
  {
    key: 'Paulina Paukštaitytė - Sapnai',
    url: '2021/Paulina Paukštaitytė - Sapnai.mp3',
    answer: 'Paulina Paukštaitytė - Sapnai',
    tag: '2021',
  },
  {
    key: 'Pendulum - Come Alive',
    url: '2021/Pendulum - Come Alive.mp3',
    answer: 'Pendulum - Come Alive',
    tag: '2021',
  },
  {
    key: 'Pushaz - Esu Čia Ir Dabar',
    url: '2021/Pushaz - Esu Čia Ir Dabar.mp3',
    answer: 'Pushaz - Esu Čia Ir Dabar',
    tag: '2021',
  },
  {
    key: 'PytRok - Mus Saugo Muzika',
    url: '2021/PytRok - Mus Saugo Muzika.mp3',
    answer: 'PytRok - Mus Saugo Muzika',
    tag: '2021',
  },
  {
    key: 'RaYnoXu - Ritmas Valdo',
    url: '2021/RaYnoXu - Ritmas Valdo.mp3',
    answer: 'RaYnoXu - Ritmas Valdo',
    tag: '2021',
  },
  {
    key: 'Rain Radio & DJ Craig Gorman - Talk About',
    url: '2021/Rain Radio & DJ Craig Gorman - Talk About.mp3',
    answer: 'Rain Radio & DJ Craig Gorman - Talk About',
    tag: '2021',
  },
  {
    key: 'Rikotumivibu ft. Aurėja BA - Tindi Rindi',
    url: '2021/Rikotumivibu ft. Aurėja BA - Tindi Rindi.mp3',
    answer: 'Rikotumivibu ft. Aurėja BA - Tindi Rindi',
    tag: '2021',
  },
  {
    key: 'Riton x Nightcrawlers - Friday',
    url: '2021/Riton x Nightcrawlers - Friday ft. Mufasa & Hypeman.mp3',
    answer: 'Riton x Nightcrawlers - Friday',
    tag: '2021',
  },
  {
    key: 'Roger Shah & Dominik Novak - Inside Out',
    url: '2021/Roger Shah & Dominik Novak - Inside Out.mp3',
    answer: 'Roger Shah & Dominik Novak - Inside Out',
    tag: '2021',
  },
  {
    key: 'RÜFÜS DU SOL - On My Knees',
    url: '2021/RÜFÜS DU SOL - On My Knees.mp3',
    answer: 'RÜFÜS DU SOL - On My Knees',
    tag: '2021',
  },
  {
    key: 'SEL feat. Soliaris - Skrendu',
    url: '2021/SEL feat. Soliaris - Skrendu.mp3',
    answer: 'SEL feat. Soliaris - Skrendu',
    tag: '2021',
  },
  {
    key: 'Sel - Tarp Sienų Keturių',
    url: '2021/Sel - Tarp Sienų Keturių.mp3',
    answer: 'Sel - Tarp Sienų Keturių',
    tag: '2021',
  },
  {
    key: 'Shouse - Love Tonight',
    url: '2021/Shouse - Love Tonight.mp3',
    answer: 'Shouse - Love Tonight',
    tag: '2021',
  },
  {
    key: 'Spada - Want You Back',
    url: '2021/Spada - Want You Back.mp3',
    answer: 'Spada - Want You Back',
    tag: '2021',
  },
  {
    key: 'Spiller ft. Sophie Ellis-Bextor - Groovejet',
    url: '2021/Spiller ft. Sophie Ellis-Bextor - Groovejet.mp3',
    answer: 'Spiller ft. Sophie Ellis-Bextor - Groovejet',
    tag: '2021',
  },
  {
    key: 'THE CUBE GUYS - Drunk',
    url: '2021/THE CUBE GUYS - Drunk.mp3',
    answer: 'THE CUBE GUYS - Drunk',
    tag: '2021',
  },
  {
    key: 'The Nights - Kill For Me',
    url: '2021/The Nights - Kill For Me.mp3',
    answer: 'The Nights - Kill For Me',
    tag: '2021',
  },
  {
    key: 'The Weeknd - Save Your Tears',
    url: '2021/The Weeknd - Save Your Tears.mp3',
    answer: 'The Weeknd - Save Your Tears',
    tag: '2021',
  },
  {
    key: 'The roop - Discoteque',
    url: '2021/The roop - Discoteque.mp3',
    answer: 'The roop - Discoteque',
    tag: '2021',
  },
  {
    key: 'Thomas Gold - Pump Up The Jam',
    url: '2021/Thomas Gold - Pump Up The Jam.mp3',
    answer: 'Thomas Gold - Pump Up The Jam',
    tag: '2021',
  },
  {
    key: 'Tiësto, Killfake - Money',
    url: '2021/Tiësto, Killfake - Money.mp3',
    answer: 'Tiësto, Killfake - Money',
    tag: '2021',
  },
  {
    key: "Tomas Lu - Don't Stop",
    url: "2021/Tomas Lu - Don't Stop.mp3",
    answer: "Tomas Lu - Don't Stop",
    tag: '2021',
  },
  {
    key: 'Tomas Lu - move on baby',
    url: '2021/Tomas Lu - move on baby.mp3',
    answer: 'Tomas Lu - move on baby',
    tag: '2021',
  },
  {
    key: 'Tujamo - Take Control',
    url: '2021/Tujamo - Take Control.mp3',
    answer: 'Tujamo - Take Control',
    tag: '2021',
  },
  {
    key: "Ugg'A - Dernière Danse",
    url: "2021/Ugg'A - Dernière Danse.mp3",
    answer: "Ugg'A - Dernière Danse",
    tag: '2021',
  },
  {
    key: 'Ummet Ozcan - Reborn',
    url: '2021/Ummet Ozcan - Reborn.mp3',
    answer: 'Ummet Ozcan - Reborn',
    tag: '2021',
  },
  {
    key: 'Vaidas Baumila - Kunigunda',
    url: '2021/Vaidas Baumila - Kunigunda.mp3',
    answer: 'Vaidas Baumila - Kunigunda',
    tag: '2021',
  },
  {
    key: 'Hiperbolė - Vandens Ženklai',
    url: '2021/Hiperbolė - Vandens Ženklai.mp3',
    answer: 'Hiperbolė - Vandens Ženklai',
    tag: '2021',
  },
  {
    key: 'Sea Shanty - Wellerman',
    url: '2021/Sea Shanty - Wellerman.mp3',
    answer: 'Sea Shanty - Wellerman',
    tag: '2021',
  },
  {
    key: 'Will Armex - You and I',
    url: '2021/Will Armex - You and I.mp3',
    answer: 'Will Armex - You and I',
    tag: '2021',
  },
  {
    key: 'Xd - HOW OLD ARE YOU',
    url: '2021/Xd - HOW OLD ARE YOU.mp3',
    answer: 'Xd - HOW OLD ARE YOU',
    tag: '2021',
  },
  {
    key: 'ZUBI - Love Zombie',
    url: '2021/ZUBI - Love Zombie.mp3',
    answer: 'ZUBI - Love Zombie',
    tag: '2021',
  },
  {
    key: 'Zafrir & Afrojack - Boom Boom Pow',
    url: '2021/Zafrir & Afrojack - Boom Boom Pow.mp3',
    answer: 'Zafrir & Afrojack - Boom Boom Pow',
    tag: '2021',
  },
  {
    key: 'bbno$ & Rich Brian - edamame',
    url: '2021/bbno$ & Rich Brian - edamame.mp3',
    answer: 'bbno$ & Rich Brian - edamame',
    tag: '2021',
  },
  {
    key: 'Баста & Zivert - неболей',
    url: '2021/Баста & Zivert - неболей.mp3',
    answer: 'Баста & Zivert - неболей',
    tag: '2021',
  },
  {
    key: 'Anne-Marie - PSYCHO',
    url: '2023/Anne-Marie - PSYCHO.mp3',
    answer: 'Anne-Marie - PSYCHO',
    tag: '2023',
  },
  {
    key: 'Ayra Starr - Rush',
    url: '2023/Ayra Starr - Rush.mp3',
    answer: 'Ayra Starr - Rush',
    tag: '2023',
  },
  {
    key: 'Beyoncé - CUFF IT',
    url: '2023/Beyoncé - CUFF IT.mp3',
    answer: 'Beyoncé - CUFF IT',
    tag: '2023',
  },
  {
    key: 'Bruno Mars - When I Was Your Man',
    url: '2023/Bruno Mars - When I Was Your Man.mp3',
    answer: 'Bruno Mars - When I Was Your Man',
    tag: '2023',
  },
  {
    key: 'Bugzy Malone - Out Of Nowhere',
    url: '2023/Bugzy Malone - Out Of Nowhere.mp3',
    answer: 'Bugzy Malone - Out Of Nowhere',
    tag: '2023',
  },
  {
    key: 'Burna Boy - Last Last',
    url: '2023/Burna Boy - Last Last.mp3',
    answer: 'Burna Boy - Last Last',
    tag: '2023',
  },
  {
    key: 'Caity Baser - Pretty Boys',
    url: '2023/Caity Baser - Pretty Boys.mp3',
    answer: 'Caity Baser - Pretty Boys',
    tag: '2023',
  },
  {
    key: 'Cat Burns - go',
    url: '2023/Cat Burns - go.mp3',
    answer: 'Cat Burns - go',
    tag: '2023',
  },
  {
    key: 'Cat Burns - people pleaser',
    url: '2023/Cat Burns - people pleaser.mp3',
    answer: 'Cat Burns - people pleaser',
    tag: '2023',
  },
  {
    key: 'Central Cee - LET GO',
    url: '2023/Central Cee - LET GO.mp3',
    answer: 'Central Cee - LET GO',
    tag: '2023',
  },
  {
    key: 'Central Cee - Me & You',
    url: '2023/Central Cee - Me & You.mp3',
    answer: 'Central Cee - Me & You',
    tag: '2023',
  },
  {
    key: 'Chris Brown - Under The Influence',
    url: '2023/Chris Brown - Under The Influence.mp3',
    answer: 'Chris Brown - Under The Influence',
    tag: '2023',
  },
  {
    key: "Cian Ducrot - I'll Be Waiting",
    url: "2023/Cian Ducrot - I'll Be Waiting.mp3",
    answer: "Cian Ducrot - I'll Be Waiting",
    tag: '2023',
  },
  {
    key: 'Coi Leray - Players',
    url: '2023/Coi Leray - Players.mp3',
    answer: 'Coi Leray - Players',
    tag: '2023',
  },
  {
    key: 'Coldplay - Viva La Vida',
    url: '2023/Coldplay - Viva La Vida.mp3',
    answer: 'Coldplay - Viva La Vida',
    tag: '2023',
  },
  {
    key: 'D-Block Europe - Barbie',
    url: '2023/D-Block Europe - Barbie.mp3',
    answer: 'D-Block Europe - Barbie',
    tag: '2023',
  },
  {
    key: "David Guetta - I'm Good",
    url: "2023/David Guetta - I'm Good.mp3",
    answer: "David Guetta - I'm Good",
    tag: '2023',
  },
  {
    key: 'Drake - Rich Flex',
    url: '2023/Drake - Rich Flex.mp3',
    answer: 'Drake - Rich Flex',
    tag: '2023',
  },
  {
    key: 'Ed Sheeran - Bad Habits',
    url: '2023/Ed Sheeran - Bad Habits.mp3',
    answer: 'Ed Sheeran - Bad Habits',
    tag: '2023',
  },
  {
    key: 'Ed Sheeran - Shivers',
    url: '2023/Ed Sheeran - Shivers.mp3',
    answer: 'Ed Sheeran - Shivers',
    tag: '2023',
  },
  {
    key: 'Eliza Rose - B.O.T.A',
    url: '2023/Eliza Rose - B.O.T.A.mp3',
    answer: 'Eliza Rose - B.O.T.A',
    tag: '2023',
  },
  {
    key: 'FLO - Cardboard Box',
    url: '2023/FLO - Cardboard Box.mp3',
    answer: 'FLO - Cardboard Box',
    tag: '2023',
  },
  {
    key: 'Freya Ridings - Weekends',
    url: '2023/Freya Ridings - Weekends.mp3',
    answer: 'Freya Ridings - Weekends',
    tag: '2023',
  },
  {
    key: 'George Ezra - Green Green Grass',
    url: '2023/George Ezra - Green Green Grass.mp3',
    answer: 'George Ezra - Green Green Grass',
    tag: '2023',
  },
  {
    key: 'Glass Animals - Heat Waves',
    url: '2023/Glass Animals - Heat Waves.mp3',
    answer: 'Glass Animals - Heat Waves',
    tag: '2023',
  },
  {
    key: 'Harry Styles - As It Was',
    url: '2023/Harry Styles - As It Was.mp3',
    answer: 'Harry Styles - As It Was',
    tag: '2023',
  },
  {
    key: 'Harry Styles - Music For a Sushi Restaurant',
    url: '2023/Harry Styles - Music For a Sushi Restaurant.mp3',
    answer: 'Harry Styles - Music For a Sushi Restaurant',
    tag: '2023',
  },
  {
    key: "Headie One - Martin's Sofa",
    url: "2023/Headie One - Martin's Sofa.mp3",
    answer: "Headie One - Martin's Sofa",
    tag: '2023',
  },
  {
    key: 'Hotel Ugly - Shut up My Moms Calling',
    url: '2023/Hotel Ugly - Shut up My Moms Calling.mp3',
    answer: 'Hotel Ugly - Shut up My Moms Calling',
    tag: '2023',
  },
  {
    key: 'Ice Spice - In Ha Mood',
    url: '2023/Ice Spice - In Ha Mood.mp3',
    answer: 'Ice Spice - In Ha Mood',
    tag: '2023',
  },
  {
    key: 'Interworld - METAMORPHOSIS',
    url: '2023/Interworld - METAMORPHOSIS.mp3',
    answer: 'Interworld - METAMORPHOSIS',
    tag: '2023',
  },
  {
    key: 'JVKE - golden hour',
    url: '2023/JVKE - golden hour.mp3',
    answer: 'JVKE - golden hour',
    tag: '2023',
  },
  {
    key: 'Jax Jones - Whistle',
    url: '2023/Jax Jones - Whistle.mp3',
    answer: 'Jax Jones - Whistle',
    tag: '2023',
  },
  {
    key: 'Jengi - Bel Mercy',
    url: '2023/Jengi - Bel Mercy.mp3',
    answer: 'Jengi - Bel Mercy',
    tag: '2023',
  },
  {
    key: 'Joel Corry - Lionheart',
    url: '2023/Joel Corry - Lionheart.mp3',
    answer: 'Joel Corry - Lionheart',
    tag: '2023',
  },
  {
    key: 'KSI - Voices',
    url: '2023/KSI - Voices.mp3',
    answer: 'KSI - Voices',
    tag: '2023',
  },
  {
    key: 'LF SYSTEM - Afraid To Feel',
    url: '2023/LF SYSTEM - Afraid To Feel.mp3',
    answer: 'LF SYSTEM - Afraid To Feel',
    tag: '2023',
  },
  {
    key: 'Lana Del Rey - A&W',
    url: '2023/Lana Del Rey - A&W.mp3',
    answer: 'Lana Del Rey - A&W',
    tag: '2023',
  },
  {
    key: 'Lewis Capaldi - Forget Me',
    url: '2023/Lewis Capaldi - Forget Me.mp3',
    answer: 'Lewis Capaldi - Forget Me',
    tag: '2023',
  },
  {
    key: 'Lewis Capaldi - Pointless',
    url: '2023/Lewis Capaldi - Pointless.mp3',
    answer: 'Lewis Capaldi - Pointless',
    tag: '2023',
  },
  {
    key: 'Lewis Capaldi - Someone You Loved',
    url: '2023/Lewis Capaldi - Someone You Loved.mp3',
    answer: 'Lewis Capaldi - Someone You Loved',
    tag: '2023',
  },
  {
    key: 'Libianca - People',
    url: '2023/Libianca - People.mp3',
    answer: 'Libianca - People',
    tag: '2023',
  },
  {
    key: 'Lil Uzi Vert - Just Wanna Rock',
    url: '2023/Lil Uzi Vert - Just Wanna Rock.mp3',
    answer: 'Lil Uzi Vert - Just Wanna Rock',
    tag: '2023',
  },
  {
    key: 'Lil Uzi Vert - Watch This',
    url: '2023/Lil Uzi Vert - Watch This.mp3',
    answer: 'Lil Uzi Vert - Watch This',
    tag: '2023',
  },
  {
    key: 'Linkin Park - Lost',
    url: '2023/Linkin Park - Lost.mp3',
    answer: 'Linkin Park - Lost',
    tag: '2023',
  },
  {
    key: 'Lizzo - Special',
    url: '2023/Lizzo - Special.mp3',
    answer: 'Lizzo - Special',
    tag: '2023',
  },
  {
    key: 'Lizzy McAlpine - ceilings',
    url: '2023/Lizzy McAlpine - ceilings.mp3',
    answer: 'Lizzy McAlpine - ceilings',
    tag: '2023',
  },
  {
    key: 'LoveJoy - Call Me What You Like',
    url: '2023/LoveJoy - Call Me What You Like.mp3',
    answer: 'LoveJoy - Call Me What You Like',
    tag: '2023',
  },
  {
    key: 'Luke Combs - The Kind of Love We Make',
    url: '2023/Luke Combs - The Kind of Love We Make.mp3',
    answer: 'Luke Combs - The Kind of Love We Make',
    tag: '2023',
  },
  {
    key: 'Mae Stephens - If We Ever Broke Up',
    url: '2023/Mae Stephens - If We Ever Broke Up.mp3',
    answer: 'Mae Stephens - If We Ever Broke Up',
    tag: '2023',
  },
  {
    key: 'Meghan Trainor - Made You Look',
    url: '2023/Meghan Trainor - Made You Look.mp3',
    answer: 'Meghan Trainor - Made You Look',
    tag: '2023',
  },
  {
    key: "Metro Boomin - Creepin'",
    url: "2023/Metro Boomin - Creepin'.mp3",
    answer: "Metro Boomin - Creepin'",
    tag: '2023',
  },
  {
    key: 'Miguel - Sure Thing',
    url: '2023/Miguel - Sure Thing.mp3',
    answer: 'Miguel - Sure Thing',
    tag: '2023',
  },
  {
    key: 'Miley Cyrus - Flowers',
    url: '2023/Miley Cyrus - Flowers.mp3',
    answer: 'Miley Cyrus - Flowers',
    tag: '2023',
  },
  {
    key: 'Mimi Webb - Red Flags',
    url: '2023/Mimi Webb - Red Flags.mp3',
    answer: 'Mimi Webb - Red Flags',
    tag: '2023',
  },
  {
    key: 'NF - HOPE',
    url: '2023/NF - HOPE.mp3',
    answer: 'NF - HOPE',
    tag: '2023',
  },
  {
    key: 'Nathan Dawe - Oh Baby',
    url: '2023/Nathan Dawe - Oh Baby.mp3',
    answer: 'Nathan Dawe - Oh Baby',
    tag: '2023',
  },
  {
    key: 'Niall Horan - Heaven',
    url: '2023/Niall Horan - Heaven.mp3',
    answer: 'Niall Horan - Heaven',
    tag: '2023',
  },
  {
    key: 'Oliver Tree - Miss You',
    url: '2023/Oliver Tree - Miss You.mp3',
    answer: 'Oliver Tree - Miss You',
    tag: '2023',
  },
  {
    key: "OneRepublic - I Ain't Worried",
    url: "2023/OneRepublic - I Ain't Worried.mp3",
    answer: "OneRepublic - I Ain't Worried",
    tag: '2023',
  },
  {
    key: 'P!nk - Never Gonna Not Dance Again',
    url: '2023/P!nk - Never Gonna Not Dance Again.mp3',
    answer: 'P!nk - Never Gonna Not Dance Again',
    tag: '2023',
  },
  {
    key: 'P!nk - TRUSTFALL',
    url: '2023/P!nk - TRUSTFALL.mp3',
    answer: 'P!nk - TRUSTFALL',
    tag: '2023',
  },
  {
    key: 'P!nk - When I Get There',
    url: '2023/P!nk - When I Get There.mp3',
    answer: 'P!nk - When I Get There',
    tag: '2023',
  },
  {
    key: "PinkPantheress - Boy's a liar Pt. 2",
    url: "2023/PinkPantheress - Boy's a liar Pt. 2.mp3",
    answer: "PinkPantheress - Boy's a liar Pt. 2",
    tag: '2023',
  },
  {
    key: 'Prinz - Beautiful Day',
    url: '2023/Prinz - Beautiful Day.mp3',
    answer: 'Prinz - Beautiful Day',
    tag: '2023',
  },
  {
    key: 'RAYE - Escapism',
    url: '2023/RAYE - Escapism.mp3',
    answer: 'RAYE - Escapism',
    tag: '2023',
  },
  {
    key: 'Rema - Calm Down',
    url: '2023/Rema - Calm Down.mp3',
    answer: 'Rema - Calm Down',
    tag: '2023',
  },
  {
    key: 'Richy Mitch & The Coal Miners - Evergreen',
    url: '2023/Richy Mitch & The Coal Miners - Evergreen.mp3',
    answer: 'Richy Mitch & The Coal Miners - Evergreen',
    tag: '2023',
  },
  {
    key: 'Rita Ora - You Only Love Me',
    url: '2023/Rita Ora - You Only Love Me.mp3',
    answer: 'Rita Ora - You Only Love Me',
    tag: '2023',
  },
  {
    key: 'SZA - Kill Bill',
    url: '2023/SZA - Kill Bill.mp3',
    answer: 'SZA - Kill Bill',
    tag: '2023',
  },
  {
    key: 'SZA - Low',
    url: '2023/SZA - Low.mp3',
    answer: 'SZA - Low',
    tag: '2023',
  },
  {
    key: 'SZA - Snooze',
    url: '2023/SZA - Snooze.mp3',
    answer: 'SZA - Snooze',
    tag: '2023',
  },
  {
    key: 'Sabrina Carpenter - Nonsense',
    url: '2023/Sabrina Carpenter - Nonsense.mp3',
    answer: 'Sabrina Carpenter - Nonsense',
    tag: '2023',
  },
  {
    key: 'Sam Fender - Seventeen Going Under',
    url: '2023/Sam Fender - Seventeen Going Under.mp3',
    answer: 'Sam Fender - Seventeen Going Under',
    tag: '2023',
  },
  {
    key: "Sam Smith - I'm Not Here To Make Friends",
    url: "2023/Sam Smith - I'm Not Here To Make Friends.mp3",
    answer: "Sam Smith - I'm Not Here To Make Friends",
    tag: '2023',
  },
  {
    key: 'Sam Smith - Unholy',
    url: '2023/Sam Smith - Unholy.mp3',
    answer: 'Sam Smith - Unholy',
    tag: '2023',
  },
  {
    key: 'Skrillex - Rumble',
    url: '2023/Skrillex - Rumble.mp3',
    answer: 'Skrillex - Rumble',
    tag: '2023',
  },
  {
    key: 'Stephen Sanchez - Until I Found You',
    url: '2023/Stephen Sanchez - Until I Found You.mp3',
    answer: 'Stephen Sanchez - Until I Found You',
    tag: '2023',
  },
  {
    key: 'Steve Lacy - Bad Habit',
    url: '2023/Steve Lacy - Bad Habit.mp3',
    answer: 'Steve Lacy - Bad Habit',
    tag: '2023',
  },
  {
    key: 'Stormzy - Hide & Seek',
    url: '2023/Stormzy - Hide & Seek.mp3',
    answer: 'Stormzy - Hide & Seek',
    tag: '2023',
  },
  {
    key: 'Strandz - Us Against the World',
    url: '2023/Strandz - Us Against the World.mp3',
    answer: 'Strandz - Us Against the World',
    tag: '2023',
  },
  {
    key: 'Sub Focus - Ready To Fly',
    url: '2023/Sub Focus - Ready To Fly.mp3',
    answer: 'Sub Focus - Ready To Fly',
    tag: '2023',
  },
  {
    key: 'Switch Disco - REACT',
    url: '2023/Switch Disco - REACT.mp3',
    answer: 'Switch Disco - REACT',
    tag: '2023',
  },
  {
    key: 'Taylor Swift - Anti-Hero',
    url: '2023/Taylor Swift - Anti-Hero.mp3',
    answer: 'Taylor Swift - Anti-Hero',
    tag: '2023',
  },
  {
    key: 'Taylor Swift - Lavender Haze',
    url: '2023/Taylor Swift - Lavender Haze.mp3',
    answer: 'Taylor Swift - Lavender Haze',
    tag: '2023',
  },
  {
    key: 'The Kid LAROI - Love Again',
    url: '2023/The Kid LAROI - Love Again.mp3',
    answer: 'The Kid LAROI - Love Again',
    tag: '2023',
  },
  {
    key: 'The Kid LAROI - STAY',
    url: '2023/The Kid LAROI - STAY.mp3',
    answer: 'The Kid LAROI - STAY',
    tag: '2023',
  },
  {
    key: 'The Killers - Mr. Brightside',
    url: '2023/The Killers - Mr. Brightside.mp3',
    answer: 'The Killers - Mr. Brightside',
    tag: '2023',
  },
  {
    key: 'The Weeknd - Blinding Lights',
    url: '2023/The Weeknd - Blinding Lights.mp3',
    answer: 'The Weeknd - Blinding Lights',
    tag: '2023',
  },
  {
    key: 'The Weeknd - Die For You',
    url: '2023/The Weeknd - Die For You.mp3',
    answer: 'The Weeknd - Die For You',
    tag: '2023',
  },
  {
    key: 'The Weeknd - Save Your Tears',
    url: '2023/The Weeknd - Save Your Tears.mp3',
    answer: 'The Weeknd - Save Your Tears',
    tag: '2023',
  },
  {
    key: 'ThxSoMch - SPIT IN MY FACE!',
    url: '2023/ThxSoMch - SPIT IN MY FACE!.mp3',
    answer: 'ThxSoMch - SPIT IN MY FACE!',
    tag: '2023',
  },
  {
    key: 'Tiësto - 10_35',
    url: '2023/Tiësto - 10_35.mp3',
    answer: 'Tiësto - 10_35',
    tag: '2023',
  },
  {
    key: 'Tom Grennan - Here',
    url: '2023/Tom Grennan - Here.mp3',
    answer: 'Tom Grennan - Here',
    tag: '2023',
  },
  {
    key: 'Tom Odell - Another Love',
    url: '2023/Tom Odell - Another Love.mp3',
    answer: 'Tom Odell - Another Love',
    tag: '2023',
  },
  {
    key: 'Tory Lanez - The Color Violet',
    url: '2023/Tory Lanez - The Color Violet.mp3',
    answer: 'Tory Lanez - The Color Violet',
    tag: '2023',
  },
  {
    key: 'beabadoobee - Glue Song',
    url: '2023/beabadoobee - Glue Song.mp3',
    answer: 'beabadoobee - Glue Song',
    tag: '2023',
  },
  {
    key: 'd4vd - Here With Me',
    url: '2023/d4vd - Here With Me.mp3',
    answer: 'd4vd - Here With Me',
    tag: '2023',
  },
  {
    key: 'venbee - messy in heaven',
    url: '2023/venbee - messy in heaven.mp3',
    answer: 'venbee - messy in heaven',
    tag: '2023',
  },
  {
    key: 'Øneheart - snowfall',
    url: '2023/Øneheart - snowfall.mp3',
    answer: 'Øneheart - snowfall',
    tag: '2023',
  },
];
